// Demo data for the application when Firebase is not connected
// This allows the app to work as a fully functional demo

export const demoUser = {
  uid: 'demo-user-1',
  email: 'alex@university.edu',
  displayName: 'Alex Johnson',
  photoURL: '',
  role: 'student' as const,
  department: 'Computer Science',
  semester: 5,
  bio: 'CS student passionate about web development and AI',
  isOnline: true,
  lastSeen: null,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const demoUsers = [
  demoUser,
  { uid: 'demo-user-2', displayName: 'Sarah Chen', email: 'sarah@university.edu', photoURL: '', role: 'student' as const, department: 'Computer Science', semester: 5, bio: 'Love coding and design', isOnline: true, lastSeen: null, createdAt: new Date(), updatedAt: new Date() },
  { uid: 'demo-user-3', displayName: 'Mike Rivera', email: 'mike@university.edu', photoURL: '', role: 'student' as const, department: 'Electronics', semester: 3, bio: 'Hardware enthusiast', isOnline: false, lastSeen: null, createdAt: new Date(), updatedAt: new Date() },
  { uid: 'demo-user-4', displayName: 'Emily Park', email: 'emily@university.edu', photoURL: '', role: 'moderator' as const, department: 'Computer Science', semester: 7, bio: 'Senior student and community mod', isOnline: true, lastSeen: null, createdAt: new Date(), updatedAt: new Date() },
  { uid: 'demo-user-5', displayName: 'Prof. Williams', email: 'williams@university.edu', photoURL: '', role: 'admin' as const, department: 'Computer Science', semester: 0, bio: 'Professor of Computer Science', isOnline: false, lastSeen: null, createdAt: new Date(), updatedAt: new Date() },
  { uid: 'demo-user-6', displayName: 'Jordan Lee', email: 'jordan@university.edu', photoURL: '', role: 'student' as const, department: 'Mathematics', semester: 4, bio: 'Math nerd who loves puzzles', isOnline: true, lastSeen: null, createdAt: new Date(), updatedAt: new Date() },
];

export const demoPosts = [
  {
    id: 'post-1',
    authorId: 'demo-user-2',
    authorName: 'Sarah Chen',
    authorPhoto: '',
    content: 'Just finished the Data Structures assignment! The AVL tree implementation was tricky but finally got all test cases passing. Anyone else struggling with the rotation logic? Happy to help! 🎉🌲',
    images: [],
    likes: ['demo-user-1', 'demo-user-3', 'demo-user-4'],
    commentCount: 5,
    tags: ['DSA', 'Assignment', 'Help'],
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'post-2',
    authorId: 'demo-user-4',
    authorName: 'Emily Park',
    authorPhoto: '',
    content: '📢 Important: The hackathon registration deadline has been extended to next Friday! We already have 20+ teams signed up. This year\'s theme is "AI for Social Good". Don\'t miss out!\n\nPrize pool: $5,000 💰\nFree food and swag! 🍕👕',
    images: [],
    likes: ['demo-user-1', 'demo-user-2', 'demo-user-3', 'demo-user-5', 'demo-user-6'],
    commentCount: 12,
    tags: ['Hackathon', 'Event', 'AI'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: 'post-3',
    authorId: 'demo-user-5',
    authorName: 'Prof. Williams',
    authorPhoto: '',
    content: 'Uploaded the lecture slides for Chapter 7: Machine Learning Fundamentals. Please review before Thursday\'s class. There will be a pop quiz! 📚\n\nAlso, office hours this week are shifted to Wednesday 2-4 PM.',
    images: [],
    likes: ['demo-user-1', 'demo-user-2'],
    commentCount: 3,
    tags: ['ML', 'Lecture', 'Important'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: 'post-4',
    authorId: 'demo-user-6',
    authorName: 'Jordan Lee',
    authorPhoto: '',
    content: 'Found an amazing resource for Discrete Mathematics! This YouTube playlist covers everything from graph theory to combinatorics. Sharing for anyone who needs it for the upcoming finals.\n\nLink in comments 👇',
    images: [],
    likes: ['demo-user-1', 'demo-user-3'],
    commentCount: 8,
    tags: ['Math', 'Resources', 'Finals'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
  },
  {
    id: 'post-5',
    authorId: 'demo-user-3',
    authorName: 'Mike Rivera',
    authorPhoto: '',
    content: 'Our IoT project just won 2nd place at the inter-college tech fest! 🏆 Built a smart campus system using Arduino and React Native. Huge thanks to the team!\n\n#ProudMoment #TechFest2026',
    images: [],
    likes: ['demo-user-1', 'demo-user-2', 'demo-user-4', 'demo-user-5', 'demo-user-6'],
    commentCount: 15,
    tags: ['Achievement', 'IoT', 'TechFest'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
];

export const demoChatRooms = [
  {
    id: 'chat-1',
    type: 'private' as const,
    name: 'Sarah Chen',
    avatar: '',
    members: ['demo-user-1', 'demo-user-2'],
    lastMessage: 'Sure, I\'ll send you the notes!',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 5),
    lastMessageBy: 'demo-user-2',
    createdBy: 'demo-user-1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
  },
  {
    id: 'chat-2',
    type: 'group' as const,
    name: 'CS Batch 2026 🎓',
    avatar: '',
    members: ['demo-user-1', 'demo-user-2', 'demo-user-4', 'demo-user-6'],
    lastMessage: 'Meeting at 5 PM in the lab!',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 15),
    lastMessageBy: 'demo-user-4',
    createdBy: 'demo-user-4',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
  },
  {
    id: 'chat-3',
    type: 'group' as const,
    name: 'Hackathon Team Alpha 🚀',
    avatar: '',
    members: ['demo-user-1', 'demo-user-2', 'demo-user-3'],
    lastMessage: 'I pushed the frontend changes',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 45),
    lastMessageBy: 'demo-user-1',
    createdBy: 'demo-user-1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
  },
  {
    id: 'chat-4',
    type: 'private' as const,
    name: 'Prof. Williams',
    avatar: '',
    members: ['demo-user-1', 'demo-user-5'],
    lastMessage: 'Your project proposal looks good. Let\'s discuss tomorrow.',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    lastMessageBy: 'demo-user-5',
    createdBy: 'demo-user-1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
  },
];

export const demoMessages: Record<string, Array<{
  id: string;
  chatRoomId: string;
  senderId: string;
  senderName: string;
  senderPhoto: string;
  text: string;
  fileAttachment: null;
  readBy: string[];
  createdAt: Date;
}>> = {
  'chat-1': [
    { id: 'msg-1', chatRoomId: 'chat-1', senderId: 'demo-user-1', senderName: 'Alex Johnson', senderPhoto: '', text: 'Hey Sarah! Did you finish the DSA assignment?', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-2'], createdAt: new Date(Date.now() - 1000 * 60 * 30) },
    { id: 'msg-2', chatRoomId: 'chat-1', senderId: 'demo-user-2', senderName: 'Sarah Chen', senderPhoto: '', text: 'Yes! Just submitted it. The AVL tree part was intense 😅', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-2'], createdAt: new Date(Date.now() - 1000 * 60 * 25) },
    { id: 'msg-3', chatRoomId: 'chat-1', senderId: 'demo-user-1', senderName: 'Alex Johnson', senderPhoto: '', text: 'Could you share your notes for the rotation algorithms?', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-2'], createdAt: new Date(Date.now() - 1000 * 60 * 20) },
    { id: 'msg-4', chatRoomId: 'chat-1', senderId: 'demo-user-2', senderName: 'Sarah Chen', senderPhoto: '', text: 'Sure, I\'ll send you the notes!', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-2'], createdAt: new Date(Date.now() - 1000 * 60 * 5) },
  ],
  'chat-2': [
    { id: 'msg-5', chatRoomId: 'chat-2', senderId: 'demo-user-6', senderName: 'Jordan Lee', senderPhoto: '', text: 'Has anyone started the math assignment?', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-6'], createdAt: new Date(Date.now() - 1000 * 60 * 60) },
    { id: 'msg-6', chatRoomId: 'chat-2', senderId: 'demo-user-1', senderName: 'Alex Johnson', senderPhoto: '', text: 'Not yet, planning to start tonight', fileAttachment: null, readBy: ['demo-user-1'], createdAt: new Date(Date.now() - 1000 * 60 * 50) },
    { id: 'msg-7', chatRoomId: 'chat-2', senderId: 'demo-user-2', senderName: 'Sarah Chen', senderPhoto: '', text: 'I can help with the calculus part if anyone needs it!', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-2'], createdAt: new Date(Date.now() - 1000 * 60 * 30) },
    { id: 'msg-8', chatRoomId: 'chat-2', senderId: 'demo-user-4', senderName: 'Emily Park', senderPhoto: '', text: 'Meeting at 5 PM in the lab!', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-4'], createdAt: new Date(Date.now() - 1000 * 60 * 15) },
  ],
  'chat-3': [
    { id: 'msg-9', chatRoomId: 'chat-3', senderId: 'demo-user-3', senderName: 'Mike Rivera', senderPhoto: '', text: 'The backend API is ready. Who\'s handling the frontend?', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-3'], createdAt: new Date(Date.now() - 1000 * 60 * 120) },
    { id: 'msg-10', chatRoomId: 'chat-3', senderId: 'demo-user-1', senderName: 'Alex Johnson', senderPhoto: '', text: 'I\'ll take care of the React components', fileAttachment: null, readBy: ['demo-user-1'], createdAt: new Date(Date.now() - 1000 * 60 * 90) },
    { id: 'msg-11', chatRoomId: 'chat-3', senderId: 'demo-user-1', senderName: 'Alex Johnson', senderPhoto: '', text: 'I pushed the frontend changes', fileAttachment: null, readBy: ['demo-user-1'], createdAt: new Date(Date.now() - 1000 * 60 * 45) },
  ],
  'chat-4': [
    { id: 'msg-12', chatRoomId: 'chat-4', senderId: 'demo-user-1', senderName: 'Alex Johnson', senderPhoto: '', text: 'Professor, I\'ve submitted my project proposal for review.', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-5'], createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3) },
    { id: 'msg-13', chatRoomId: 'chat-4', senderId: 'demo-user-5', senderName: 'Prof. Williams', senderPhoto: '', text: 'Your project proposal looks good. Let\'s discuss tomorrow.', fileAttachment: null, readBy: ['demo-user-1', 'demo-user-5'], createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2) },
  ],
};

export const demoHomework = [
  {
    id: 'hw-1',
    title: 'AVL Tree Implementation',
    description: 'Implement an AVL tree with insert, delete, and search operations. Include proper rotation methods and balance factor computation.',
    subject: 'Data Structures & Algorithms',
    semester: 5,
    department: 'Computer Science',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2),
    attachments: [],
    createdBy: 'demo-user-5',
    createdByName: 'Prof. Williams',
    status: 'active' as const,
    submissions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
  },
  {
    id: 'hw-2',
    title: 'Machine Learning Lab Report',
    description: 'Write a detailed lab report on the linear regression experiment conducted in class. Include data analysis, model evaluation metrics, and conclusions.',
    subject: 'Machine Learning',
    semester: 5,
    department: 'Computer Science',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5),
    attachments: [],
    createdBy: 'demo-user-5',
    createdByName: 'Prof. Williams',
    status: 'active' as const,
    submissions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
  },
  {
    id: 'hw-3',
    title: 'Database Normalization Exercise',
    description: 'Normalize the given database schema to 3NF. Show all functional dependencies and decomposition steps.',
    subject: 'Database Management',
    semester: 5,
    department: 'Computer Science',
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1),
    attachments: [],
    createdBy: 'demo-user-5',
    createdByName: 'Prof. Williams',
    status: 'overdue' as const,
    submissions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
  },
];

export const demoExams = [
  {
    id: 'exam-1',
    title: 'Data Structures Midterm',
    subject: 'Data Structures & Algorithms',
    semester: 5,
    department: 'Computer Science',
    date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7),
    duration: 180,
    venue: 'Hall A, Block 3',
    type: 'midterm' as const,
    syllabus: 'Arrays, Linked Lists, Stacks, Queues, Trees, AVL Trees, Heaps',
    createdBy: 'demo-user-5',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
  },
  {
    id: 'exam-2',
    title: 'Machine Learning Quiz 3',
    subject: 'Machine Learning',
    semester: 5,
    department: 'Computer Science',
    date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3),
    duration: 60,
    venue: 'Room 205, CS Block',
    type: 'quiz' as const,
    syllabus: 'Linear Regression, Logistic Regression, SVM',
    createdBy: 'demo-user-5',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
  },
  {
    id: 'exam-3',
    title: 'DBMS Final Exam',
    subject: 'Database Management',
    semester: 5,
    department: 'Computer Science',
    date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 21),
    duration: 180,
    venue: 'Auditorium, Main Block',
    type: 'final' as const,
    syllabus: 'Complete Syllabus - ER Diagrams, Normalization, SQL, Transactions, Concurrency',
    createdBy: 'demo-user-5',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10),
  },
];

export const demoAnnouncements = [
  {
    id: 'ann-1',
    title: 'Campus Wi-Fi Upgrade',
    content: 'The campus Wi-Fi network will undergo maintenance this Saturday from 6 AM to 12 PM. Please plan your online activities accordingly. The new network will support Wi-Fi 6E with speeds up to 2.4 Gbps.',
    priority: 'high' as const,
    category: 'Infrastructure',
    authorId: 'demo-user-5',
    authorName: 'Prof. Williams',
    attachments: [],
    readBy: ['demo-user-1'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
  {
    id: 'ann-2',
    title: 'Hackathon 2026 Registration Open',
    content: 'Register now for the annual Inter-College Hackathon! This year\'s theme is "AI for Social Good". Teams of 2-4 members. Prize pool: $5,000. Free meals and swag for all participants.',
    priority: 'medium' as const,
    category: 'Event',
    authorId: 'demo-user-4',
    authorName: 'Emily Park',
    attachments: [],
    readBy: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
  },
  {
    id: 'ann-3',
    title: 'Library Hours Extended During Finals',
    content: 'The central library will remain open 24/7 during the finals week (June 1-14). Student ID required for entry after 10 PM. Free coffee and snacks available from 8 PM.',
    priority: 'low' as const,
    category: 'Academic',
    authorId: 'demo-user-5',
    authorName: 'Prof. Williams',
    attachments: [],
    readBy: ['demo-user-1'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
];

export const demoFiles = [
  {
    id: 'file-1',
    fileId: 'drive-abc123',
    fileName: 'DSA_Chapter5_Notes.pdf',
    fileType: 'pdf',
    fileSize: 2450000,
    driveUrl: '#',
    thumbnailUrl: '',
    category: 'notes' as const,
    subject: 'Data Structures & Algorithms',
    semester: 5,
    uploadedBy: 'demo-user-2',
    uploaderName: 'Sarah Chen',
    downloads: 45,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
  },
  {
    id: 'file-2',
    fileId: 'drive-def456',
    fileName: 'ML_Lab_Manual.pdf',
    fileType: 'pdf',
    fileSize: 5120000,
    driveUrl: '#',
    thumbnailUrl: '',
    category: 'notes' as const,
    subject: 'Machine Learning',
    semester: 5,
    uploadedBy: 'demo-user-5',
    uploaderName: 'Prof. Williams',
    downloads: 89,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
  },
  {
    id: 'file-3',
    fileId: 'drive-ghi789',
    fileName: 'DBMS_Assignment2.pdf',
    fileType: 'pdf',
    fileSize: 1280000,
    driveUrl: '#',
    thumbnailUrl: '',
    category: 'assignment' as const,
    subject: 'Database Management',
    semester: 5,
    uploadedBy: 'demo-user-5',
    uploaderName: 'Prof. Williams',
    downloads: 32,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
  },
  {
    id: 'file-4',
    fileId: 'drive-jkl012',
    fileName: 'DSA_Midterm_2025.pdf',
    fileType: 'pdf',
    fileSize: 890000,
    driveUrl: '#',
    thumbnailUrl: '',
    category: 'question_paper' as const,
    subject: 'Data Structures & Algorithms',
    semester: 5,
    uploadedBy: 'demo-user-4',
    uploaderName: 'Emily Park',
    downloads: 120,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
  },
  {
    id: 'file-5',
    fileId: 'drive-mno345',
    fileName: 'CS_Syllabus_Sem5.pdf',
    fileType: 'pdf',
    fileSize: 340000,
    driveUrl: '#',
    thumbnailUrl: '',
    category: 'syllabus' as const,
    subject: 'Computer Science',
    semester: 5,
    uploadedBy: 'demo-user-5',
    uploaderName: 'Prof. Williams',
    downloads: 200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60),
  },
];

export const demoQuestionBank = [
  {
    id: 'qb-1',
    title: 'DSA Midterm 2025',
    subject: 'Data Structures & Algorithms',
    semester: 5,
    year: 2025,
    type: 'midterm' as const,
    file: demoFiles[3],
    uploadedBy: 'demo-user-4',
    uploaderName: 'Emily Park',
    downloads: 120,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
  },
  {
    id: 'qb-2',
    title: 'ML Final 2025',
    subject: 'Machine Learning',
    semester: 5,
    year: 2025,
    type: 'final' as const,
    file: demoFiles[1],
    uploadedBy: 'demo-user-5',
    uploaderName: 'Prof. Williams',
    downloads: 89,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60),
  },
  {
    id: 'qb-3',
    title: 'DBMS Quiz Collection 2024-2025',
    subject: 'Database Management',
    semester: 5,
    year: 2025,
    type: 'quiz' as const,
    file: demoFiles[2],
    uploadedBy: 'demo-user-4',
    uploaderName: 'Emily Park',
    downloads: 65,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45),
  },
  {
    id: 'qb-4',
    title: 'DSA Final 2024',
    subject: 'Data Structures & Algorithms',
    semester: 5,
    year: 2024,
    type: 'final' as const,
    file: demoFiles[0],
    uploadedBy: 'demo-user-2',
    uploaderName: 'Sarah Chen',
    downloads: 156,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180),
  },
];

export const demoNotifications = [
  { id: 'notif-1', userId: 'demo-user-1', type: 'like' as const, title: 'New Like', body: 'Sarah Chen liked your post', link: '/feed', read: false, createdAt: new Date(Date.now() - 1000 * 60 * 10) },
  { id: 'notif-2', userId: 'demo-user-1', type: 'comment' as const, title: 'New Comment', body: 'Mike Rivera commented on your post', link: '/feed', read: false, createdAt: new Date(Date.now() - 1000 * 60 * 30) },
  { id: 'notif-3', userId: 'demo-user-1', type: 'homework' as const, title: 'New Homework', body: 'ML Lab Report due in 5 days', link: '/dashboard', read: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3) },
  { id: 'notif-4', userId: 'demo-user-1', type: 'announcement' as const, title: 'Announcement', body: 'Campus Wi-Fi Upgrade this Saturday', link: '/dashboard', read: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4) },
  { id: 'notif-5', userId: 'demo-user-1', type: 'exam' as const, title: 'Exam Reminder', body: 'ML Quiz 3 in 3 days', link: '/dashboard', read: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6) },
];

export const demoStats = {
  totalStudents: 1247,
  totalPosts: 3456,
  totalFiles: 892,
  activeChats: 156,
  weeklyActivity: [
    { day: 'Mon', posts: 45, messages: 230, files: 12 },
    { day: 'Tue', posts: 52, messages: 280, files: 18 },
    { day: 'Wed', posts: 38, messages: 190, files: 8 },
    { day: 'Thu', posts: 65, messages: 340, files: 22 },
    { day: 'Fri', posts: 48, messages: 260, files: 15 },
    { day: 'Sat', posts: 22, messages: 120, files: 5 },
    { day: 'Sun', posts: 18, messages: 90, files: 3 },
  ],
  departmentDistribution: [
    { name: 'Computer Science', value: 420, color: '#6366f1' },
    { name: 'Electronics', value: 280, color: '#8b5cf6' },
    { name: 'Mechanical', value: 210, color: '#a78bfa' },
    { name: 'Civil', value: 180, color: '#c4b5fd' },
    { name: 'Mathematics', value: 157, color: '#ddd6fe' },
  ],
};
